#!/usr/bin/env python

import os

programs = """
kr_wayland_test.c
""".split()

programs2 = """
kr_wayland_test2.c
""".split()

programs3 = """
kr_pool_test.c
""".split()

includedirs = """
../../lib/krad_mem/
../../lib/krad_calc/
../../lib/krad_compositor/
../../lib/krad_chronometer/
../../lib/krad_coder/
../../lib/krad_player/
../../lib/krad_xmms2/
../../lib/krad_y4m/
../../lib/krad_framepool/
../../lib/krad_web/
../../lib/krad_web/ext/
../../lib/krad_web/ext/libwebsockets/
../../lib/krad_web/res/
../../lib/krad_vhs/
../../lib/krad_sfx/
../../lib/krad_tone/
../../lib/krad_ipc/
../../lib/krad_tags/
../../lib/krad_audio/
../../lib/krad_theora/
../../lib/krad_jack/
../../lib/krad_alsa/
../../lib/krad_mixer/
../../lib/krad_osc/
../../lib/krad_xmms2/
../../lib/krad_wayland/
../../lib/krad_vpx/
../../lib/krad_v4l2/
../../lib/krad_flac/
../../lib/krad_vorbis/
../../lib/krad_opus/
../../lib/krad_radio/
../../lib/krad_ring/
../../lib/krad_ogg/
../../lib/krad_io/
../../lib/krad_transponder/
../../lib/krad_transmitter/
../../lib/krad_container/
../../lib/krad_x11/
../../lib/krad_udp/
../../lib/krad_system/
../../lib/krad_decklink/
../../lib/krad_ebml/
../../lib/krad_legacy/
/usr/local/include
/usr/include
""".split()

shlibs = ["cairo", "wayland-client", "xkbcommon"]
depsources = ["../lib/krad_wayland/krad_wayland.c"]

depsources2 = ["../lib/krad_compositor/krad_vector.c",
               "../lib/krad_compositor/krad_compositor_subunit.c",
               "../lib/krad_chronometer/krad_easing.c"]

depsources3 = ["../lib/krad_mem/krad_pool.c"]

stlibs = []
syslibs = ['m', 'dl', 'z']
syslibs2 = ['rt']

def configure(conf):

  global programs
  global shlibs
  global shlibs2
  global syslibs

  if conf.env['KRAD_USE_WAYLAND']:
    for l in syslibs:
      conf.check(lib = l, cflags='-Wall', uselib_store = l)

    for l in shlibs:
      conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')

    for l in stlibs:
      conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs --static')

def build(bld):

  global programs
  global shlibs
  global shlibs2
  global syslibs
  global syslibs2

  if bld.env['KRAD_USE_WAYLAND']:
    for p in programs:
      bld(features = 'c cprogram',
      source = [p] + depsources,
      includes = includedirs,
      target = p.replace(".c", ""),
      use = ["kradradio_client"],
      uselib = shlibs + stlibs + syslibs)

  if bld.env['KRAD_USE_WAYLAND']:
    for p in programs2:
      bld(features = 'c cprogram',
      source = [p] + depsources + depsources2,
      includes = includedirs,
      target = p.replace(".c", ""),
      use = ["kradradio_client"],
      uselib = shlibs + stlibs + syslibs)

  for p in programs3:
    bld(features = 'c cprogram',
    source = [p] + depsources3,
    includes = includedirs,
    target = p.replace(".c", ""),
    use = ["kradradio_client"],
    uselib = shlibs + stlibs + syslibs)
